version: '3.3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    expose:
      - '2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.0.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - '9092:9092'
    expose: 
      - '29092'
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  event:
    depends_on:
      - broker
      - db    
    links:
      - db:db
      - broker:broker  
    build: event
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'    
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      KAFKA_HOST: 'broker:9092'

  invoice:
    depends_on:
      - broker
      - db    
    links:
      - db:db 
      - broker:broker 
    build: invoice
    restart: always
    environment:
      KAFKA_HOST: 'broker:9092'
      
  ticket:
    depends_on:
      - broker
      - db
    links:
      - db:db
      - broker:broker
    build: ticket
    restart: always
    ports: 
        - '8081:8080'
    expose: 
        - '8080'
    environment:
        MYSQL_HOST: 'db'
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        KAFKA_HOST: 'broker'

volumes:
  my-db:
