apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
  - name: "29092"
    port: 29092
    targetPort: 29092
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
