apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: event
  name: event
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: event
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: event
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: broker:9092
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_HOST
          value: eventdb
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_USER
          value: user
        image: manfredsteyertest/event
        imagePullPolicy: "Always"
        name: event
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
