apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ticketdb
  name: ticketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ticketdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ticketdb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: user
        image: mysql:5.7
        imagePullPolicy: ""
        name: ticketdb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: my-ticket-db
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: my-ticket-db
        persistentVolumeClaim:
          claimName: my-ticket-db
status: {}
