apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service-name-5
  namespace: default
spec:
  ports:
  - name: nameme-01
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: demo-29
  type: NodePort

#This is Pod Configuration Kube definition
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo-29
  namespace: default
spec:
  containers:
  - env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: '2181'
    - name: ZOOKEEPER_TICK_TIME
      value: '2000'
    image: confluentinc/cp-zookeeper:6.0.0
    imagePullPolicy: IfNotPresent
    name: zookeeper
    ports:
    - containerPort: 2181
      name: portname-0
      protocol: TCP
  hostname: zookeeper
  terminationGracePeriodSeconds: 0